### ISSUE TITLE
Why you feleted my GamerROM 8 OS?

### ISSUE THREAD

**Issue by GamerROMInc** [romhut/romhut.com#28]
Why did you remove my files?

**Comment by MatthewBooth** [comment]
They were demonstrated to be "kanging" (repackaging and taking credit) another's work which was also hosted on the site. I believe the owners of the original work had instructed you to freely compile their source code yourself rather than taking their packaged zip and redistributing.

Please follow their instructions [here](https://github.com/AOSP-JF/platform_manifest) and compile the ROM from source. RomHut takes Kanging seriously and investigates reports.

**Comment by GamerROMInc** [comment]
No work wasnt tooken from anyone as you notice gamerrom 8  is using The CM SRC Not tgeirs so taking my rom down is wrong

**Comment by GamerROMInc** [comment]
Neither from anyone as you see my kernel src is in my github

**Comment by MatthewBooth** [comment]
The evidence given was as such
- [This image](http://s3.postimg.org/wij7y1kg3/2015_09_18.png) clearly shows you using another kernel.
- format.sh script in install/bin was taken from Team JDC's ROM.
- modified loki.sh in system/etc was taken from Team JDC's ROM
- RIL blobs in system/blobs were taken from Team JDC's ROM

There was also a secret file placed by Team JDC designed to catch out kangers (at which I am not at liberty to describe) that was found as well. Had you build from source there wouldn't be this file as it is their secret file designed just for finding kangers. 

Their code is fully AOSP but they reserve the right to their compiled versions, which is their right. You are free to download the source and compile yourself. I am having difficulty understanding why you don't just do this to avoid these kinds of issues.

**Comment by smeroni68** [comment]
There is only a reason for that: he is not able to do it!

**Comment by AntaresOne** [comment]
@pspgodman you're not GPL compliant as what you call _"kernel source"_ is CyanogenMod's jflte kernel source which absolutely is not the right one for **our own custom kernel**, referring to the image you have stolen from our [Optimized CyanogenMod 12.1](https://romhut.com/roms/Optimized-CM-121). Contains TONS of commits more than CM's, therefore you're basically giving to the users something that neither you know how it's made, what there's inside, issues, how many things work (it's a kernel for advanced users) and so on.

**Kernel info shows name of the kernel, hostname of the build system which built it, user for that hostname and build date as 16 August. Why these are the same infos available in [Optimized CM 12.1 20150817](https://romhut.com/versions/optimizedcm-12-1-20150817-jflte-zip) kernel?**

As @MatthewBooth pointed out, there are many other things you stolen from our zips. Did you get a permission? You asked once and remember what I told? "No, we don't allow this but if you want you can build from our source, even if releasing your zips would mean re-releasing something already publicly available and also for the same platform. Make your own modifications on the code, build, release and link your modified source.". **A "no" means "NO", you cannot act without any regard.**

It's kinda unacceptable when you spend time working on something which will be stolen and re-released as his own work by someone. The secret file @MatthewBooth said has been made to protect our works against kangers, you're justifying yourself but **why we found that file in your zip?**

You did this dirty game too many times and for too long. It's time to stop.

**Comment by g7755725** [comment]
Really you toom the time to write that crap well idc what you say i have other resources other tgen ROMHut to host my os on BTW ROMHut cannot say its kanging and delete my rom.because their is no terms of agreement of doing so as well deketing a rom without a terms of agreement is voided and wrong to do, TERMS OF SERVICE PROTECTS YOUR WORK NOT YOU OR ANYONE ELSE everything from rules, laws etc are in that the PRIVACY POLICY only states for your privacy in personnal info witch scott didnt create on his own its detailed in protecting your privacy/personnal info NOT Your Personnal Work or  also further more  if no yerms of agreement=No RULES, NO REASON TO DELETE FILES AND MUST GIVE NOFICATIONS TO THAT DEV or a simple warninng not just delete them so as stated idc what you say because to me its like a bunch a bullshit that is just words so it doesnt bother me

**Comment by g7755725** [comment]
And why did hereopen this it really isnt that important

**Comment by scottrobertson** [comment]
We don't have to notify anyone, since we have not agreed to those terms and conditions with you. We can delete what we want, they are our servers, again, because we have not agreed to any terms with you.

Anyway, you were given plenty of warnings to stop stealing people work, and you failed to do so.

I reopened it to give you a chance to explain your actions, but you seem to just want to act like a child.

**Comment by MatthewBooth** [comment]
You kanged flies. It was demonstrated to us a number of times and you
failed to comply and stop.

RomHut doesn't have to host your files, just like you don't have to steal
other people's work, debloat and add some magical build.prop tweaks and
call it a gaming ROM.

We wish you all the best in the future.

**Comment by scottrobertson** [comment]
> And why did hereopen this it really isnt that important

You may not value other people's time and effort, but we do.

**Comment by AntaresOne** [comment]
@pspgodman 
Let me tell you that you're a great liar and think to be sly, but you're not. 
You did it many times, many times we tried to solve what's wrong with you in gentle manners and a friendly way.
Nothing back from you, until the other day when I asked for at least a well deserved credit for OUR WORK.
Your answer was "Uhh i see im using it it works pretty well and as well because i keep screwing up with my permissions", this is so offensive and disrespectful.
I don't know what kind of person you are, but due to our experience......... Even try to impersonate us, what would have been your reaction after:
- seeing your own work made only with your effort, repeatedly stolen
- dealing with someone which treats you like an idiot and does false statements publicly like what you did here
- you're the lead developer of a project and someone takes you the piss

Anthony, 
I don't know who you are neither what you are, if you are sane or insane. Even if I'm nobody to judge people I act without mincing words, saying what I think. This time you exceeded my patience.

I don't want to see anymore a single prebuilt file stolen from our zips inside your stuff. If you have more to say my address is antaresone@antaresone.eu, this is RomHut's issue tracker which doesn't regard you anymore as you've been informed about why your files have been deleted. I wish you all the best.
